### ISSUE TITLE
script or instructions for downloading all the RFCs

### ISSUE THREAD

**Issue by sbenthall** [npdoty/rfc-analysis#3]
There are currently no scripts or instructions to support this critical step:

`download all RFCs as .txt into a RFC-all directory within the main directory of the repository`

**Comment by sbenthall** [comment]
Looks like this is the place:
https://www.rfc-editor.org/retrieve/bulk/

**Comment by npdoty** [comment]
Good point. I've updated the documentation, to include a link to that bulk download page and to provide the `ietf mirror` option.
